name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Deploy
        run: |
          cd ~/deploy
          docker compose pull
          docker compose up -d