name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  approve:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "Approvazione richiesta"

  deploy:
    needs: approve
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd ~/deploy
          docker compose pull
          docker compose up -d